# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-27 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to='belt_app.User'),
        ),
    ]
